polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

pruebafiware/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^simpleform/', include('simple_form.urls', namespace="simple_form")),
]

simple_form/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.FirstMessageView.as_view(), name='first'),
    url(r'^known/$', views.KnownUserView.as_view(), name='known'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):
    	return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):
    	return self.choice_text

simple_form/models.py
from django.db import models

# Create your models here.

simple_form/forms.py
from django import forms
from nocaptcha_recaptcha.fields import NoReCaptchaField

from django.conf import settings

class MessageForm(forms.Form):
    message = forms.CharField(label="Write Message", max_length=100, error_messages={'required': 'Please, enter a message.'})
    if settings.USE_CAPTCHA:
        captcha = NoReCaptchaField(label='', error_messages={'required': 'Captcha validation is required'})

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

simple_form/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.core.urlresolvers import reverse

from .forms import MessageForm

from time import gmtime, strftime

# Now we're using Class-based views

class FirstMessageView(FormView):
    template_name = 'simple_form/name.html'
    form_class = MessageForm
    success_url = '/simpleform/known'

    def render_to_response(self, context):
        # if there is a cookie, redirect to KnownUserView
        if ('last_message' and 'date') in self.request.session:
            return HttpResponseRedirect('/simpleform/known')
        return super(FirstMessageView, self).render_to_response(context)      

    def form_valid(self, form):
        # save field in user cookie
        self.request.session['last_message'] = form.cleaned_data['message']
        self.request.session['date'] = strftime("%A, %d %b %Y %H:%M:%S", gmtime())
        return super(FirstMessageView, self).form_valid(form)

class KnownUserView(FormView):
    template_name = 'simple_form/result.html'
    form_class = MessageForm
    success_url = '/simpleform/known'

    def render_to_response(self, context):
        # if there is no cookie, redirect to FirstMessageView
        if not ('last_message' and 'date') in self.request.session:
            return HttpResponseRedirect('/simpleform')
        return super(KnownUserView, self).render_to_response(context)

    def form_valid(self, form):
        # update field in user cookie
        self.request.session['last_message'] = form.cleaned_data['message']
        self.request.session['date'] = strftime("%A, %d %b %Y %H:%M:%S", gmtime())
        return super(KnownUserView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        # save field in context for the template to render correctly
        context = super(KnownUserView, self).get_context_data(**kwargs)
        if ('last_message' and 'date') in self.request.session:
            context['message'] = self.request.session['last_message']
            context['date'] = self.request.session['date']
        return context

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

simple_form/templates/simple_form/base.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'simple_form/style.css' %}" />

{% block head_message %}{% endblock %}

<form action="{% block form_action %}{% endblock %}" method="post">
	{% csrf_token %}
	{% if form.non_field_errors or form.message.errors or form.captcha.errors %}
		<p class="errorlist">Errors:</p>
    	{{ form.non_field_errors }}
    	{{ form.message.errors }}
    	{{ form.captcha.errors }}
    {% endif %}
    <div class="fieldWrapper">

        {{ form.message.label_tag }}
        {{ form.message }}
    </div>
    <div class="fieldWrapper">

        {{ form.captcha.label_tag }}
        {{ form.captcha }}
    </div>
    <input type="submit" value="Send message" />
</form>

<script src="https://www.google.com/recaptcha/api.js" async defer></script>

<footer>
	Federico A. Fernández Moreno
</footer>

simple_form/templates/simple_form/name.html
{% extends 'simple_form/base.html' %}

{% block head_message %}<p>This is your first message</p>{% endblock %}

{% block form_action %}{% url 'simple_form:first' %}{% endblock %}

simple_form/templates/simple_form/result.html
{% extends 'simple_form/base.html' %}

{% block head_message %}
	<p class="last">Your last message was "<b>{{ message }}</b>"<br>
		and it dates from <b>{{ date }}</b>
	</p>
{% endblock %}

{% block form_action %}{% url 'simple_form:known' %}{% endblock %}